# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List Directory Contents
        run: ls -R  # List all files and directories to verify the structure

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify your desired Ruby version

      - name: Install dependencies
        run: |
          gem install bundler --user-install          # Install Bundler for the user
          bundle install                               # Install dependencies
          bundle exec jekyll build --source . --destination _site  # Build the site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'  # Upload the built site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
